### ISSUE TITLE
Resolution not matching up with Mac's Retina Screen

### ISSUE THREAD

**Issue by simonwangao** [StevenReiss/bubbles#2]
It seems that the CodeBubbles doesn't match with MacBook's resolution (or just setting to high resolution), making it blurry and eye-hurting when working on it.

**Comment by StevenReiss** [comment]
I finally got a chance to investigate this a little.  My guess is that the problem is in the Java monospace font.  If you change the code font  (Options: Code Editor Options: Default font for Code) to “PT Mono” or a different monospaced font of your choosing, it appears crisper.  Using the latest version of Java and Eclipse also helps.
